xcopy /f /y ..\NFTCalvi\src\app\authent\*.* src\app\authent\
xcopy /f /y ..\NFTCalvi\src\app\splash\*.* src\app\splash\
xcopy /f /y ..\NFTCalvi\src\app\input\*.* src\app\input\
xcopy /f /y ..\NFTCalvi\src\app\signature\*.* src\app\signature\
xcopy /f /y ..\NFTCalvi\src\app\payment\*.* src\app\payment\
xcopy /f /y ..\NFTCalvi\src\app\tuto\*.* src\app\tuto\
xcopy /f /y ..\NFTCalvi\src\app\selkey\*.* src\app\selkey\
xcopy /f /y ..\NFTCalvi\src\app\genlink\*.* src\app\genlink\
xcopy /f /y ..\NFTCalvi\src\app\autovalidator\*.* src\app\autovalidator\
xcopy /f /y ..\NFTCalvi\src\app\faqs\*.* src\app\faqs\
xcopy /f /y ..\NFTCalvi\src\app\link\*.* src\app\link\

xcopy /f /y ..\NFTCalvi\src\app\token-selector\*.* src\app\token-selector\
xcopy /f /y ..\NFTCalvi\src\app\showroom\*.* src\app\showroom\
xcopy /f /y ..\NFTCalvi\src\app\about\*.* src\app\about\
xcopy /f /y ..\NFTCalvi\src\app\authent-dialog\*.* src\app\authent-dialog\
xcopy /f /y ..\NFTCalvi\src\app\prompt\*.* src\app\prompt\
xcopy /f /y ..\NFTCalvi\src\app\ask-for-payment\*.* src\app\ask-for-payment\
xcopy /f /y ..\NFTCalvi\src\app\alias.pipe.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\splash\*.* src\app\splash\
xcopy /f /y ..\NFTCalvi\src\app\network.service.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\api.service.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\evm-wallet-service.service.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\safe.pipe.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\filter.pipe.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\translate.pipe.ts src\app\

xcopy /f /y ..\NFTCalvi\src\app\device.service.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\file-drag-ndrop.directive.ts src\app\
#xcopy /f /y ..\NFTCalvi\src\app\user.service.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\style-manager.service.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\screencutter.pipe.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\hourglass\*.*  src\app\hourglass\
xcopy /f /y ..\NFTCalvi\src\app\scanner\*.*  src\app\scanner\
xcopy /f /y ..\NFTCalvi\src\app\upload-file\*.*  src\app\upload-file\
xcopy /f /y ..\NFTCalvi\src\create.ts src\
xcopy /f /y ..\NFTCalvi\src\operation.ts src\

xcopy /f /y ..\NFTCalvi\src\tools.ts src\
xcopy /f /y ..\NFTCalvi\src\crypto.ts src\
xcopy /f /y ..\NFTCalvi\src\nft.ts src\
xcopy /f /y ..\NFTCalvi\src\definitions.ts src\
#xcopy /f /y ..\NFTCalvi\run_server.bat .
xcopy /f /y ..\NFTCalvi\src\nfluent.ts src\
xcopy /f /y ..\NFTCalvi\src\nfluent.scss src\
xcopy /f /y ..\NFTCalvi\src\nfluent-dark.scss src\
xcopy /f /y ..\NFTCalvi\src\styles.scss src\
